# Generated by Django 4.0.1 on 2022-01-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_customer', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('nomor_hp', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='menuKopi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar', models.CharField(max_length=30)),
                ('nama_kopi', models.CharField(max_length=30)),
                ('harga', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pesanan', models.IntegerField()),
                ('jumlah_pesanan', models.IntegerField()),
                ('total_harga', models.IntegerField()),
                ('sudah_bayar', models.BooleanField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customer')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.menukopi')),
            ],
        ),
    ]
